minor: 优化获取Agent状态接口
TencentBlueKing/bk-log pull request #1445
Opened 2022-09-15 08:49 UTC by OrenZhang

2022-09-15 09:12 UTC, OrenZhang commented on apps/log_search/handlers/biz.py
> +        set_local_param("request", request)
线程内无法获取Request对象

2022-09-15 09:12 UTC, OrenZhang commented on apps/log_search/handlers/biz.py
> +        set_local_param("request", request)
线程内无法获取Request对象

2022-09-15 10:55 UTC, benero approved these changes
LGTM

2022-09-16 03:48 UTC, jayjiahua commented on apps/log_search/handlers/biz.py
> +            for node, host_list in result_dict.items()
执行类的循环不建议用列表生成式，可读性不好

2022-09-16 03:48 UTC, jayjiahua commented on apps/log_search/handlers/biz.py
> +            [node_mapping.get(node).get("bk_inst_name") for node in node_mapping.get(map_key, {}).get("node_link", [])]
`node_mapping.get(node).get("bk_inst_name")`

第一个get没有默认值，如果不存在就直接抛异常了

2022-09-16 03:56 UTC, liuwenping requested changes

2022-09-16 03:56 UTC, liuwenping commented on apps/log_search/handlers/biz.py
> +        agent_multi_execute = MultiExecuteFunc()
需要考虑并发量的控制，不然对方会被拉爆

2022-09-16 07:57 UTC, liuwenping approved these changes

2022-09-16 09:16 UTC, merged