Clustering subscription
TencentBlueKing/bk-log pull request #1731
Opened 2023-01-03 07:32 UTC by wyyalt

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +        if now.minute % freq["run_time"]["minutes"] != 0:
同上，如果某一分钟错过了运行怎么办

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    data = custom_params_valid(serializer=SearchAttrSerializer, params=params)
自己内部构造的参数，就不用再走序列化器了

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    result["end_time"] = end_time.strftime(time_fmt)
时间建议先进行末位对齐，比如10分钟的查询周期，就对10取整，如 00-10, 10-20

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    return {signature: result["list"][0]["log"]}
这里逻辑有问题
1. 并不能保证每个索引都有 `log` 字段，叫其他名字也有可能
2. 所取的字段并不一定是用来做聚类的字段

建议换一种实现方式，从同步pattern的逻辑入手，获取model_file的时候实际上是能拿到原始日志的，只是我们没有保存下来，如果保存下来这里就直接可以用了

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    result["end_time"] = end_time.strftime(time_fmt)
似乎没有考虑自然日的需求？

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +        "keyword": "*",
配置的查询条件没有带进去

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    patterns = patterns[: config.size]
如果不用截取，size该如何配置？

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    for _data in result:
上面同比过滤跑了循环，这里又跑一次循环，还不如放到同一个loop里面处理

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    content = (
不建议用string format ，用模版引擎，定义一个模版文件渲染出来。这样后续好扩展

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +        "keyword": "*",
查询条件没带上

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/models.py
> +    bk_biz_id = models.IntegerField(_("业务ID"), db_index=True, max_length=64)
新的模型，建议存space_uid，而不是bk_biz_id

2023-01-03 11:53 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +    <p>{start_time}-{end_time} {title}</p>
同上，建议用模版渲染的方式。后面要是再加一些css，这里就搞不定了

2023-01-03 12:44 UTC, liuwenping requested changes

2023-01-03 12:44 UTC, liuwenping commented on apps/log_clustering/migrations/0016_clusteringsubscription.py
> +# Generated by Django 3.2.15 on 2022-12-30 07:24
新文件需要增加License头

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/models.py
> +    space_uid = models.CharField(_("空间ID"), db_index=True, max_length=64)
space_uid最大长度是256，参考其他模型的定义

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/serializers.py
> +    pattern_level = serializers.ChoiceField(required=True, choices=PatternEnum.get_dict_choices().keys())
直接 get_choices 就行了，serializer 是支持接收二元组列表的

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/serializers.py
> +    pattern_level = serializers.ChoiceField(required=True, choices=PatternEnum.get_dict_choices().keys())
同上

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +            freq["run_time"].split(":")[:2]
由于队列堵塞错过了执行时间，那么这个周期就不再执行

===

这个问题还是没有解决

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/templates/clustering_mail.html
> +<!DOCTYPE html>
模版写在根目录的template下

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/templates/clustering_wechat.md
> +{% if langeuage = 'en' %}
模版写在根目录的template下

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_clustering/templates/clustering_mail.html
> +    <p>Biz Name:   {{ bk_biz_name }}</p>
英文版建议定义一个新的模版文件，在一个模版里面 if-else 有点乱

2023-01-09 12:50 UTC, jayjiahua commented on apps/log_search/models.py
> +        configs[GlobalTypeEnum.LOG_CLUSTERING_LEVEL.value] = PatternEnum.get_dict_choices().keys()
keys返回的是个生成器，要手动转成 list

2023-01-09 12:50 UTC, jayjiahua commented on config/default.py
> +BKAPP_WECHAT_WEB_HOOK_URL = os.getenv("BKAPP_WECHAT_WEB_HOOK_URL", "")
环境变量名称要带 BKAPP 前缀，但 settings 变量名不需要，否则引用的时候会显得很长

2023-01-09 13:02 UTC, jayjiahua commented on apps/log_clustering/tasks/subscription.py
> +        for receiver in receivers:
多个chatid可用 `|` 进行拼接，调用一次API即可

2023-02-06 02:47 UTC, closed without merging