Feature admin: 日志清洗
TencentBlueKing/bk-log pull request #89
Opened 2021-08-05 09:44 UTC by EvildoerXiaoyy

2021-08-05 10:06 UTC, zzhutianyu requested changes

2021-08-05 11:32 UTC, zzhutianyu requested changes

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/handlers/clean.py
> +        return [bkdata_clean.result_table_name for bkdata_clean in BKDataClean.objects.filter(raw_data_id=raw_data_id)]
可以直接用values_list取出来

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/handlers/clean.py
> +        return (
可以改成
```
qs = CleanTemplate.objects.filter(name=name, bk_biz_id=bk_biz_id)
if self.data:
    qs = qs..exclude(clean_template_id=self.clean_template_id)
return qs.exists()
```

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/handlers/collector.py
> +        CleanStash.objects.filter(collector_config_id=self.collector_config_id).delete()
delete需要有日志

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/models.py
> +        return [
values_list

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/utils/bkdata_clean.py
> +        logger.info("insert BKDataClean collector_config_id {}".format(collector_config_id))
这个日志应该加上插入的信息

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/utils/bkdata_clean.py
> +            logger.info("delete index_sey {}".format(delete_obj.log_index_set_id))
sey是啥

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/utils/clean.py
> +                logger.error("can not find this collector_config {}".format(bk_data_clean.collector_config_id))
不continue?

2021-08-05 11:32 UTC, zzhutianyu commented on apps/log_databus/utils/clean.py
> +        return arrow.get(datetime).to(settings.TIME_ZONE).strftime(settings.BKDATA_DATETIME_FORMAT)
这个函数time_handler里面有吧

2021-08-05 13:39 UTC, EvildoerXiaoyy commented on apps/log_databus/handlers/clean.py
> +        return self.data.delete()
done

2021-08-05 13:41 UTC, EvildoerXiaoyy commented on apps/log_databus/handlers/clean.py
> +        self.data.save()
done

2021-08-05 13:41 UTC, EvildoerXiaoyy commented on apps/log_databus/tasks/bkdata.py
> +                "raw_data_name": collector_config.collector_config_name_en or collector_config.table_id.split(".")[1],
done

2021-08-05 13:42 UTC, EvildoerXiaoyy commented on apps/log_databus/utils/clean.py
> +        if keyword in clean.collector_config_name or keyword in clean.result_table_id:
done

2021-08-05 13:44 UTC, EvildoerXiaoyy commented on apps/log_databus/handlers/clean.py
> +        return [bkdata_clean.result_table_name for bkdata_clean in BKDataClean.objects.filter(raw_data_id=raw_data_id)]
done

2021-08-05 13:46 UTC, EvildoerXiaoyy commented on apps/log_databus/handlers/clean.py
> +        return (
done

2021-08-05 13:47 UTC, EvildoerXiaoyy commented on apps/log_databus/handlers/collector.py
> +        CleanStash.objects.filter(collector_config_id=self.collector_config_id).delete()
done

2021-08-05 13:51 UTC, EvildoerXiaoyy commented on apps/log_databus/models.py
> +        return [
done

2021-08-05 13:54 UTC, EvildoerXiaoyy commented on apps/log_databus/utils/bkdata_clean.py
> +            logger.info("delete index_sey {}".format(delete_obj.log_index_set_id))
done

2021-08-05 13:54 UTC, EvildoerXiaoyy commented on apps/log_databus/utils/clean.py
> +                logger.error("can not find this collector_config {}".format(bk_data_clean.collector_config_id))
done

2021-08-06 01:13 UTC, zzhutianyu approved these changes

2021-08-06 03:38 UTC, merged